server:
  port: 7000
spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      routes:
        - id: svr-hoteles
          #lb:// cuando se va acceder a traves de eureka
          uri: lb://api-hoteles # direcion de la api -> http://localhot:9000
          predicates:
            - Path=/shoteles/**
          filters:
            - RewritePath=/shoteles/*, /

        - id: svr-vuelos
          uri: lb://api-vuelos
          predicates:
            - Path=/svuelos/**
          filters:
            - RewritePath=/svuelos/*, /

        - id: svr-reservas
          uri: lb://api-reservas
          predicates:
            - Path=/sreservas/**
          filters:
            - RewritePath=/sreservas/*, /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
